### PR TITLE
Misc. Animations

### PR DESCRIPTION
**Pull request by K40N**
(See issue for details)

### CODE REVIEW

**Comment by K40N** [comment]
I think it would be cool for two things to happen:
1. Loading dialog animated in and out. 
2. The totals and then the graph stuff slide up from the top into place and sort of stack on top of each other.

Before I do the second one I have to keep the totals hidden when loading (I'm going to try moving it into it's own component also, which should be nicer anyway). 

I do have a cool sheen animation (well I think it's cool) right now.

**Comment by K40N** [comment]
Oh, and @JackBlake-zkq I spent a good while trying to blur the background while the dialog was open and I think the only way to do it is with a bunch of hacky JavaScript I don't think we should bother with. 

There's a `backdrop-filter` property that does exactly what we want but it's only in like the actual latest nightly version of browsers. On Firefox iirc you even need to set a config flag. I tried recreating it in a very silly way with the `element()` CSS construct, but that didn't work either. 

The TLDR is that blurring the background when the dialog is open seems way too hard, but for example dimming it isn't. The problem with that is that we can't animate it. There's literally an MDN tutorial for animated dialog backdrops and it doesn't work on my browser. And Svelte can't interact with it since it's a pseudo-element. 

There might be some crazy way to have a parent `div` setting a CSS variable overriden by Svelte on the dialog itself for which the pseudo-element inherits variables, but I don't really want to spend more time on this.

**Comment by K40N** [comment]
I think it would be better to just have:
1. Empty except for header and loading dialog animates in
2. Loading dialog animates out
3. Totals and graph stuff slide into place

**Review by JackBlake-zkq — CHANGES_REQUESTED** [review]
This animation looks great 🔥🐐 Yeah no need to get a backdrop working, not worth it.

Only issue is this seems to break the single-array view somehow. The Graph component shows only the graph (doesn't show the array selector, unit selector, instructions, description, or image): 

Screen Shot 2023-11-21 at 1 10 27 AM

**Comment by JackBlake-zkq** [comment]
> I think it would be better to just have:
> 
> 1. Empty except for header and loading dialog animates in
> 2. Loading dialog animates out
> 3. Totals and graph stuff slide into place

That sounds good to me

**Comment by K40N** [comment]
It's in a place I like now, but ofc feedback is much appreciated. :)

**Review by JackBlake-zkq — APPROVED** [review]
Clean 🥵 

I think we should have the graph instructions and unit selection above the image + description. We can merge this and mess around with that more closer to our next meeting

**Comment by K40N** [comment]
Sounds good, merging now.

**Pull request merged**
