### PR TITLE
Image on bottom + hint (PR)

### PR DESCRIPTION
**Pull request by K40N**
See issue #38

### CODE REVIEW

**Review by JackBlake-zkq — CHANGES_REQUESTED** [review]
Looks like this is busted on chrome 💀

Also I think the hint should:
- be a bit smaller
- maybe pop up only when the bottom of the screen is below the graph? right now it feels like it directs you to the graph, but users might still miss the image/desc. Not sure on this though

**Comment by K40N** [comment]
First of all, thanks for letting me know about the Chrome thing, I'll try to fix it soon. I'm curious how since I didn't do use any nonstandard stuff (or so I thought). 

Making it smaller would be good to, I agree with that and it should be easy to do. 

As for the last comment, I'm not sure about this but I definitely see where you're coming from. Not having show up if it's already visible bc you have a weird screen size would be nice too. Rewording it might be beneficial tho, something simple like "More details below" could better convey that there's... more details below. Maybe something to play around with a little. Also let me know if I misunderstood anything. :) 

I probably won't be able to work on this until tomorrow evening just since I have a lot going on. Should be done before the Coulliard meeting tho.

**Comment by K40N** [comment]
Just to clarify: tomorrow meaning today (Wednesday).

**Comment by JackBlake-zkq** [comment]
Sounds good 👍

**Comment by K40N** [comment]
@JackBlake-zkq I'm running it in chrome and everything seems fine. How did you trigger the bug & what happened?

**Comment by K40N** [comment]
In the meantime I made it so that the message doesn't go away until you scroll down to where (>1/2 of) the image is actually visible. All that should be left is the mysterious chrome bug and making it smaller.

**Comment by K40N** [comment]
Ok, should be good to go. :)

**Review by JackBlake-zkq — APPROVED** [review]
Look great 👍 Can no longer repro chrome bug so I think we are good

**Pull request merged**
