### PR TITLE
Fix formatting (*Wh and currency)

### LINKED ISSUE #20: Use different units (kWh, MWh, etc.) AND show currency as money
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-1facce79-7fff-593c-301b-b501d75fe3ef">

Requested Change | Rough Plan
-- | --
Instead of having K, M, etc. at the end of the number of kWh, switch the unit between Wh, kWh, MWh, etc. | Should be able to format the number as we are now, check if it ends in a letter, and stick that letter in front of “Wh” to get the unit. Just remember to special-case making the “k” in “kWh” lowercase.

</div>

### PR DESCRIPTION
**Pull request by residualentropy**
Fixes #20

### CODE REVIEW

**Comment by residualentropy** [comment]
Ah, I forgot to add the logic to handle if there's <1 kWh. Now it says <last-digit>Wh as the unit

**Comment by residualentropy** [comment]
Gimme a sec to fix that

**Comment by residualentropy** [comment]
LGTM, if anyone can review this when they get a chance that would be great. :)

**Review by JackBlake-zkq — APPROVED** [review]
This looks really good and your implementation is very clean. 

Later on we might want to remove the decimal on the dollar value, since to totals will gain a figure or two when we add the big array in.

**Comment by residualentropy** [comment]
Sounds good, I'll go do that soon.

**Comment by residualentropy** [comment]
Sorry one sec, it also did it for the currency value in the "$0.10 saved per ..." text.

**Comment by residualentropy** [comment]
Alright, that should be fixed now. I'm going to merge it.

**Pull request merged**
